routes/web.php
<?php

use App\Models\Department;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('departments', \App\Http\Controllers\DepartmentController::class);
Route::resource('employees', \App\Http\Controllers\EmployeeController::class);

Route::get('/test', function () {
    $avg = Department::query()->with('depHasMany2')->first();
//    $d->increment('count_of_employees');
    dd($avg);
});
Route::get('/2', function () {
//    function generate_code($length)
//    {
//        $chars = 'qwertyuiopasdfghjklzxcvbnm1234567890QQWERTYUIOPASDFGHKLZXCVBNM';
//        $numChars = strlen($chars); // Узнаем, сколько у нас задано символов
//        $str = '';
//        for ($i = 0; $i < $length; $i++) {
//            $str .= substr($chars, rand(1, $numChars) - 1, 1);
//        } // Генерируем код
//
//        // Перемешиваем, на всякий случай
//        $array_mix = preg_split('//', $str, -1, PREG_SPLIT_NO_EMPTY);
//        srand((float)microtime() * 1000000);
//        shuffle($array_mix);
//        // Возвращаем полученный код
//        return implode("", $array_mix);
//    }
//    dd(generate_code(6));
//    $timestamp = strtotime('20.05.2022');
//
//    $day = date('D', $timestamp);
//    var_dump($day);

    function findStringDate($string)
    {
        $week = ['Sun' => 'вс', 'Mon' => 'пн', 'Tue' => 'вт', 'Wed' => 'ср', 'Thu' => 'чт', 'Fri' => 'пт', 'Sat' => 'сб'];

        $pattern = "/\d{2}\.\d{2}\.\d{4}/";
        if (preg_match_all($pattern, $string, $matches)) {
            foreach (array_unique($matches[0]) as $value) {
                $timestamp = strtotime($value);
                $day = $week[date('D', $timestamp)];

                $string = str_replace($value, $value . ' (' . $day . ')', $string);
            }
        }
        return $string;
    }

    var_dump(findStringDate('Давайте устроим встречу 20.05.2022 и потом ещё одну 12.06.2022'));

});

app/Models/Employee.php
<?php

namespace App\Models;

use App\Observers\EmployeeObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class Employee extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot();

        static::saved(function ($emp) {
            Log::info("Entereddddddddddddddddddddddddddddddddddddddddd");
            foreach ($emp->dep_emp as $item) {
                $item->update([
                    'avg__salary' => $item->emp_dep->avg('salary'),
                    'count_of_employees' => $item->emp_dep->count(),
                ]);
            }
        });
//        self::observe(EmployeeObserver::class);
    }

    public function dep_emp()
    {
        return $this->belongsToMany(Department::class, 'employee_departments');
    }

    public function depHasMany()
    {
        return $this->hasMany(EmployeeDepartment::class, 'employee_id');
    }

    public function depHasMany2()
    {
        return $this->hasManyThrough(EmployeeDepartment::class, Department::class, 'id', 'department_id', 'id', 'id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeRequest;
use App\Http\Resources\EmployeeResource;
use App\Http\Resources\EmpResource;
use App\Models\Employee;
use App\Services\DepartmentService;
use App\Services\EmployeeService;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;

class EmployeeController extends Controller
{
    private DepartmentService $departmentService;
    private EmployeeService $employeeService;

    public function __construct(DepartmentService $departmentService, EmployeeService $employeeService)
    {
        $this->departmentService = $departmentService;
        $this->employeeService = $employeeService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        $dep = $this->employeeService->getAll(true);
        return view('pages.employee.list', compact('dep'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        $dep = $this->departmentService->getAll();
        return view('pages.employee.create', compact('dep'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $result = $this->employeeService->createDep($request->validated());
        if (!$result) {
            return Response::fail(['fail' => ['Something went wrong']], 'Failed');
        }
        return Response::success('Successful', route('employees.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Employee $employee
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(Employee $employee)
    {
        $dep = $this->departmentService->getAll();
        $employee = $this->employeeService->getDep($employee);
        return view('pages.employee.update', compact('employee', 'dep'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, Employee $employee)
    {
        $result = $this->employeeService->updateEmp($employee, $request->validated());
        if (!$result) {
            return Response::fail(['fail' => ['Something went wrong']], 'Failed');
        }
        return Response::success('Successful', route('employees.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Employee $employee
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Employee $employee)
    {
        $this->employeeService->deleteEmp($employee);
        return redirect()->back();
    }
}

resources/views/pages/employee/create.blade.php
@extends('layouts.app')
@section('content')
    <main class="flex-shrink-0" style="padding-top: 70px">
        <div class="container">
            <h1>Employee Create</h1>
            <div class="depc"></div>
            <form action="{{route('employees.store')}}" method="post" id="create_employee">
                @csrf
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Name</label>
                    <input type="text" class="form-control" name="name" value="{{old('name')}}">
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Surname</label>
                    <input type="text" class="form-control" name="surname" value="{{old('surname')}}">
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Father name</label>
                    <input type="text" class="form-control" name="father_name" value="{{old('father_name')}}">
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Gender</label>
                    <br>
                    Male
                    <input type="radio" name="gender" value="1" @if(old('gender',1) == 1) checked @endif>
                    Female
                    <input type="radio" name="gender" value="2" @if(old('gender') == 2) checked @endif>
                </div>
                <label for="salary">Salary</label>
                <input type="tel" name="salary" value="{{old('salary')}}">
                <br>
                <br>
                <label for="deb">Departments</label>
                <br>
                @foreach($dep as $d)
                    <label for="dep">
                        {{$d->name}}</label>
                    <input type="checkbox" name="dep[]" value="{{$d->id}}"><br>
                @endforeach
                <br>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </main>
@endsection

resources/views/pages/employee/list.blade.php
@extends('layouts.app')
@section('content')
    <main class="flex-shrink-0" style="padding-top: 70px">
        <div class="container">
            <a class="btn btn-primary" href="{{route('employees.create')}}">Add</a>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Father name</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Salary</th>
                    <th scope="col">Departments</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($dep as $d)
                    <tr>
                        <th scope="row">{!! $d->id !!}</th>
                        <td>{{$d->name}}</td>
                        <td>{{$d->surname}}</td>
                        <td>{{$d->father_name}}</td>
                        <td>{{$d->gender ? 'Male' : 'Female'}}</td>
                        <td>{{$d->salary}}</td>
                        <td>{{ $d->dep_emp->pluck('name')->implode(',')}}</td>
                        <td>
                            <form action="{{route('employees.destroy',['employee'=>$d->id])}}" method="post">
                                @csrf
                                @method('delete')
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                            <a class="btn btn-success"
                               href="{{route('employees.edit',['employee'=>$d->id])}}">Edit</a>
                        </td>
                    </tr>
                @endforeach
                {{$dep->links('pagination::bootstrap-4')}}
                </tbody>
            </table>
        </div>
    </main>
@endsection

resources/views/pages/employee/update.blade.php
@extends('layouts.app')
@section('content')
    <main class="flex-shrink-0" style="padding-top: 70px">
        <div class="container">
            <h1>Employee Update</h1>
            <div class="depu"></div>
            <form action="{{route('employees.update',['employee'=>$employee->id])}}" method="post"
                  id="update_department">
                @csrf
                @method('put')
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Name</label>
                    <input type="text" class="form-control" name="name" value="{{old('name',$employee->name)}}">
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Surname</label>
                    <input type="text" class="form-control" name="surname"
                           value="{{old('surname',$employee->surname)}}">
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Father name</label>
                    <input type="text" class="form-control" name="father_name"
                           value="{{old('father_name',$employee->father_name)}}">
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Gender</label>
                    <br>
                    Male
                    <input type="radio" name="gender" value="1"
                           @if(old('gender',$employee->gender) == 1) checked @endif>
                    Female
                    <input type="radio" name="gender" value="2"
                           @if(old('gender',$employee->gender) == 2) checked @endif>
                </div>
                <label for="salary">Salary</label>
                <input type="tel" name="salary" value="{{old('salary',$employee->salary)}}">
                <br>
                <br>
                <label for="deb">Departments</label>
                <br>
                @php
                    $v = $employee->dep_emp->pluck('id')->toArray();
                @endphp
                @foreach($dep as $d)
                    <label for="dep">
                        {{$d->name}}</label>
                    <input type="checkbox" name="dep[]" {{in_array($d->id,$v) ? 'checked' : ''}} value="{{$d->id}}"><br>
                @endforeach
                <br>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </main>
@endsection