routes/web.php
<?php

use App\Models\Department;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('departments', \App\Http\Controllers\DepartmentController::class);
Route::resource('employees', \App\Http\Controllers\EmployeeController::class);

Route::get('/test', function () {
    $avg = Department::query()->with('depHasMany2')->first();
//    $d->increment('count_of_employees');
    dd($avg);
});
Route::get('/2', function () {
//    function generate_code($length)
//    {
//        $chars = 'qwertyuiopasdfghjklzxcvbnm1234567890QQWERTYUIOPASDFGHKLZXCVBNM';
//        $numChars = strlen($chars); // Узнаем, сколько у нас задано символов
//        $str = '';
//        for ($i = 0; $i < $length; $i++) {
//            $str .= substr($chars, rand(1, $numChars) - 1, 1);
//        } // Генерируем код
//
//        // Перемешиваем, на всякий случай
//        $array_mix = preg_split('//', $str, -1, PREG_SPLIT_NO_EMPTY);
//        srand((float)microtime() * 1000000);
//        shuffle($array_mix);
//        // Возвращаем полученный код
//        return implode("", $array_mix);
//    }
//    dd(generate_code(6));
//    $timestamp = strtotime('20.05.2022');
//
//    $day = date('D', $timestamp);
//    var_dump($day);

    function findStringDate($string)
    {
        $week = ['Sun' => 'вс', 'Mon' => 'пн', 'Tue' => 'вт', 'Wed' => 'ср', 'Thu' => 'чт', 'Fri' => 'пт', 'Sat' => 'сб'];

        $pattern = "/\d{2}\.\d{2}\.\d{4}/";
        if (preg_match_all($pattern, $string, $matches)) {
            foreach (array_unique($matches[0]) as $value) {
                $timestamp = strtotime($value);
                $day = $week[date('D', $timestamp)];

                $string = str_replace($value, $value . ' (' . $day . ')', $string);
            }
        }
        return $string;
    }

    var_dump(findStringDate('Давайте устроим встречу 20.05.2022 и потом ещё одну 12.06.2022'));

});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot();
    }

    public function emp_dep()
    {
        return $this->belongsToMany(Employee::class, 'employee_departments');
    }

    public function depHasMany()
    {
        return $this->hasMany(EmployeeDepartment::class, 'department_id');
    }

    public function depHasMany2()
    {
        return $this->hasManyThrough(EmployeeDepartment::class, Employee::class, 'id', 'employee_id', 'id', 'id');
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DepartmentRequest;
use App\Http\Resources\DepartmentResource;
use App\Models\Department;
use App\Services\DepartmentService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class DepartmentController extends Controller
{
    private DepartmentService $departmentService;

    public function __construct(DepartmentService $departmentService)
    {
        $this->departmentService = $departmentService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory
     */
    public function index()
    {
        $dep = $this->departmentService->getAll(true);
        return view('pages.department.list', compact('dep'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory
     */
    public function create()
    {
        return view('pages.department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(DepartmentRequest $request)
    {
        $result = $this->departmentService->createDep($request->validated());
        if (!$result) {
            return Response::fail(['fail' => ['Something went wrong']], 'Failed');
        }
        return Response::success('Successful', route('departments.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department)
    {
        $department = $this->departmentService->getDep($department);
        return view('pages.department.update', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Department $department
     * @return \Illuminate\Http\Response
     */
    public function update(DepartmentRequest $request, Department $department)
    {
        $result = $this->departmentService->updateDep($department, $request->validated());
        if (!$result) {
            return Response::fail(['fail' => ['Something went wrong']], 'Failed');
        }
        return Response::success('Successful', route('departments.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Department $department)
    {
        $result = $this->departmentService->deleteDep($department);
        if (!$result) {
            return redirect()->back()->with('error', 'This Department has employees');
        }
        return redirect()->route('departments.index')->with('success', 'Successfully');
    }
}

resources/views/pages/department/create.blade.php
@extends('layouts.app')
@section('content')
    <main class="flex-shrink-0" style="padding-top: 70px">
        <div class="container">
            <h1>Department Create</h1>
            <div class="depc"></div>
            <form action="{{route('departments.store')}}" method="post" id="create_department">
                @csrf
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Name</label>
                    <input type="text" class="form-control" name="name" value="{{old('name')}}">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </main>
@endsection

resources/views/pages/department/list.blade.php
@extends('layouts.app')
@section('content')
    <main class="flex-shrink-0" style="padding-top: 70px">
        <div class="container">
            <a class="btn btn-primary" href="{{route('departments.create')}}">Add</a>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Number of employees</th>
                    <th scope="col">AVG salary among employees</th>
                </tr>
                </thead>
                <tbody>
                @if(session()->has('error'))
                    <div class="alert alert-danger">
                        {{ session()->get('error') }}
                    </div>
                @endif
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                @foreach($dep as $d)
                    <tr>
                        <th scope="row">{!! $d->id !!}</th>
                        <td>{{$d->name}}</td>
                        <td>{{$d->count_of_employees}}</td>
                        <td>{{$d->avg__salary}}</td>
                        <td>
                            <form action="{{route('departments.destroy',['department'=>$d->id])}}" method="post">
                                @csrf
                                @method('delete')
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                            <a class="btn btn-success"
                               href="{{route('departments.edit',['department'=>$d->id])}}">Edit</a>
                        </td>
                    </tr>
                @endforeach
                {{$dep->links('pagination::bootstrap-4')}}
                </tbody>
            </table>
        </div>
    </main>
@endsection

resources/views/pages/department/update.blade.php
@extends('layouts.app')
@section('content')
    <main class="flex-shrink-0" style="padding-top: 70px">
        <div class="container">
            <h1>Department Update</h1>
            <div class="depu"></div>
            <form action="{{route('departments.update',['department'=>$department->id])}}" method="post"
                  id="update_department">
                @csrf
                @method('put')
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Name</label>
                    <input type="text" class="form-control" name="name" value="{{old('name',$department->name)}}">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </main>
@endsection