routes/web.php
<?php

use App\Models\Department;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('departments', \App\Http\Controllers\DepartmentController::class);
Route::resource('employees', \App\Http\Controllers\EmployeeController::class);

Route::get('/test', function () {
    $avg = Department::query()->with('depHasMany2')->first();
//    $d->increment('count_of_employees');
    dd($avg);
});
Route::get('/2', function () {
//    function generate_code($length)
//    {
//        $chars = 'qwertyuiopasdfghjklzxcvbnm1234567890QQWERTYUIOPASDFGHKLZXCVBNM';
//        $numChars = strlen($chars); // Узнаем, сколько у нас задано символов
//        $str = '';
//        for ($i = 0; $i < $length; $i++) {
//            $str .= substr($chars, rand(1, $numChars) - 1, 1);
//        } // Генерируем код
//
//        // Перемешиваем, на всякий случай
//        $array_mix = preg_split('//', $str, -1, PREG_SPLIT_NO_EMPTY);
//        srand((float)microtime() * 1000000);
//        shuffle($array_mix);
//        // Возвращаем полученный код
//        return implode("", $array_mix);
//    }
//    dd(generate_code(6));
//    $timestamp = strtotime('20.05.2022');
//
//    $day = date('D', $timestamp);
//    var_dump($day);

    function findStringDate($string)
    {
        $week = ['Sun' => 'вс', 'Mon' => 'пн', 'Tue' => 'вт', 'Wed' => 'ср', 'Thu' => 'чт', 'Fri' => 'пт', 'Sat' => 'сб'];

        $pattern = "/\d{2}\.\d{2}\.\d{4}/";
        if (preg_match_all($pattern, $string, $matches)) {
            foreach (array_unique($matches[0]) as $value) {
                $timestamp = strtotime($value);
                $day = $week[date('D', $timestamp)];

                $string = str_replace($value, $value . ' (' . $day . ')', $string);
            }
        }
        return $string;
    }

    var_dump(findStringDate('Давайте устроим встречу 20.05.2022 и потом ещё одну 12.06.2022'));

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <meta name="csrf-token" content="{{csrf_token()}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <script src="{{asset('/css/pivot.css')}}"></script>
</head>
<body class="d-flex flex-column h-100">
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Fixed navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{route('home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('departments.index')}}">Department</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('employees.index')}}">Employees</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
@yield('content')
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
<script src="{{asset('/js/own.js')}}"></script>
<script src="{{asset('/js/pivot.js')}}"></script>
@yield('js')
</body>
</html>